export const settings = {
  name: 'Monish Patalay', shortName: 'MP', email: 'officialmonishh@gmail.com', location: 'Los Angeles, CA',
  roleLines: ['AI Engineer', 'Full-Stack Developer', 'Builds and ships end to end'],
  eyebrow: 'M.S. Computer Science · Cal State LA · Aug 2024 – May 2026',
  statementHeading: 'A builder at heart.',
  statementNote: 'Curious by default. Hands-on by choice.',
  statement: 'I like the space where a good idea becomes something you can actually use. I build across the stack—from the model and the API to the last interaction on the screen. Thoughtful engineering. Useful AI. Things that work.',
  phone: '+1 (626) 692-4003',
  resumeUrl: 'https://resume.monishpatalay.dev', github: 'https://github.com/monishpatalay', linkedin: 'https://www.linkedin.com/in/monish-patalay/',
  availability: { status: 'hidden', text: '' },
  suggestedPrompts: ['What has Monish built with AI?', 'What is his strongest project?', 'Which technologies does he use?', 'What did he do at DRDO?'],
};
export type Project = { _id: string; slug: string; title: string; category: string; summary: string; techs: string[]; featured: boolean; year?: number; image?: string; previewPlaybackId?: string; previewThumbTime?: number; imageKind: string; color: string; symbol: string; role: string; status: string; github?: string; live?: string; metrics: {value: string; label: string; sourceNote: string}[]; sections: {title: string; text: string}[]; body?: unknown[] };
export const projects: Project[] = [
  { _id:'project-cook', slug:'cook', title:'Cook', category:'full-stack', summary:'Less deciding. More cooking. An AI agent that turns three answers into a week of meals.', techs:['React','TypeScript','Node.js','MongoDB','Vercel AI SDK'], featured:true, imageKind:'promo', color:'#c7e6aa', symbol:'✳', role:'Full-stack development', status:'Built', github:'https://github.com/monishpatalay/Meal-Planner-AI-App', live:'https://cook.monishpatalay.dev', metrics:[{value:'21',label:'meal slots per plan',sourceNote:'PRD §9.1; live résumé'},{value:'20+',label:'REST endpoints',sourceNote:'PRD §9.1; live résumé'},{value:'3',label:'questions to a plan',sourceNote:'PRD §9.1; live résumé'}], sections:[{title:'Problem',text:'Planning a week of meals means balancing preferences, finding recipes, and making the same decisions repeatedly. Cook brings that workflow into one place.'},{title:'Constraints',text:'Generated plans must fit seven days and twenty-one meal slots. Third-party services can fail, and private meal plans and billing data need clear ownership boundaries.'},{title:'Approach',text:'Milo collects three answers before generating a structured plan. Zod validates the output, and a deterministic fallback keeps planning available when the model fails. Concurrent recipe searches use Promise.allSettled so one unavailable source does not discard the other result.'},{title:'Architecture',text:'React and TypeScript → Express REST API → MongoDB. The server connects to OpenRouter through the Vercel AI SDK, recipe providers, and Stripe. Provider keys remain server-side.'},{title:'Challenges and trade-offs',text:'An LLM makes planning flexible but introduces uncertainty. Schema validation and a deterministic fallback trade some variety for predictable behavior. JWT authentication, bcrypt, ownership checks, rate limits, and signed billing webhooks protect the application boundaries.'},{title:'Results',text:'The application includes eight pages and more than twenty REST endpoints, with a conversational flow that creates a seven-day plan. These are implementation facts, not claims about adoption.'},{title:'What I would do next',text:'Measure the quality of generated meal plans with repeatable evaluation cases, especially dietary constraints and provider failures.'}] },
  { _id:'project-crop-expert', slug:'crop-expert', title:'Crop Expert', category:'ai-ml', summary:'A leaf, a photo, a clearer answer. Plant disease recognition from model to browser.', techs:['TensorFlow','FastAPI','React','Python'], featured:true, imageKind:'promo', color:'#d5efba', symbol:'⌁', role:'Machine learning & full-stack development', status:'Deployed', github:'https://github.com/monishpatalay/Crop-Expert', live:'https://crop-expert.monishpatalay.dev', metrics:[{value:'94.9%',label:'test accuracy',sourceNote:'PRD §9.1; single held-out split, no cross-validation'},{value:'8',label:'plant classes',sourceNote:'PRD §9.1'},{value:'9,612',label:'training dataset images',sourceNote:'PRD §9.1; PlantVillage'}], sections:[{title:'Problem',text:'Plant disease recognition becomes more useful when a trained model is available through a simple image-upload workflow.'},{title:'Constraints',text:'The model recognises eight classes. The reported test accuracy comes from a single dataset split, without cross-validation; it should not be read as field accuracy on arbitrary plants.'},{title:'Approach',text:'A six-block convolutional neural network processes leaf images. A React and TypeScript interface sends an upload to FastAPI for preprocessing and inference.'},{title:'Architecture',text:'React on Vercel → FastAPI on Render → image preprocessing → TensorFlow CNN → class probabilities. An alternate TensorFlow Serving configuration supports versioned model serving.'},{title:'Challenges and trade-offs',text:'A hardcoded fifteen-class API mapping conflicted with the eight-class model. Defensive class slicing fixed the mismatch and prevented silent misclassification. Explicit input contracts matter as much as the model score.'},{title:'Results',text:'The CNN reached 94.9% test accuracy across eight classes using 9,612 PlantVillage images. The application exposes the model through a deployed browser-to-API workflow.'},{title:'What I would do next',text:'Evaluate real-world images, run cross-validation, and add uncertainty handling before extending the class set.'}] },
  { _id:'project-cinematch', slug:'cinematch', title:'CineMatch', category:'ai-ml', summary:'Your next movie, minus the endless scrolling. Recommendations with zero runtime API calls.',techs:['Next.js','Python','scikit-learn','TypeScript'], featured:true,image:'/images/cinematch.webp',imageKind:'promo',color:'#c7b5f1',symbol:'◉',role:'Recommendation system & web development',status:'Deployed', github:'https://github.com/monishpatalay/Movie-Recommender-System', live:'https://cinematch.monishpatalay.dev', metrics:[{value:'~4,800',label:'movies',sourceNote:'PRD §9.1; repository'},{value:'5',label:'recommendations',sourceNote:'PRD §9.1; repository'},{value:'0',label:'runtime API calls',sourceNote:'PRD §9.1; repository'}],sections:[{title:'Problem',text:'Finding a similar movie should be quick, with recommendations that do not require an account or another paid API request.'},{title:'Constraints',text:'The deployed site must work without a TMDb secret. Recommendations should be reproducible and fast to serve.'},{title:'Approach',text:'Plot, genre, cast and crew metadata are combined into features. CountVectorizer produces bag-of-words vectors, and cosine similarity selects five nearby titles.'},{title:'Architecture',text:'TMDb metadata → offline Python feature pipeline → cosine-similarity ranking → precomputed JSON → static Next.js interface.'},{title:'Challenges and trade-offs',text:'Precomputing removes runtime provider dependencies and key exposure. The trade-off is a fixed catalogue that requires an offline rebuild for new movies. This is distinct from the TF-IDF recommender built during the DRDO internship.'},{title:'Results',text:'Roughly 4,800 movies are searchable with five recommendations per title. Python and TypeScript checks cover both sides of the pipeline.'},{title:'What I would do next',text:'Compare recommendation quality against alternative feature representations and add a reproducible catalogue refresh process.'}] },
  { _id:'project-spotify',slug:'spotify-library-organizer',title:'Spotify Library Organizer',category:'full-stack',summary:'Turn a natural-language prompt into a library that fits your mood.',techs:['React','Node.js','Claude Haiku','Spotify API'],featured:false,imageKind:'promo',color:'#b9ebce',symbol:'≋',role:'Full-stack & AI development',status:'Built', github:'https://github.com/monishpatalay/Spotify-Library-Organizer-App', live:'https://spotify.monishpatalay.dev', metrics:[],sections:[{title:'Problem',text:'Large music libraries are difficult to organise manually.'},{title:'Approach',text:'A hybrid regex and Claude Haiku pipeline classifies tracks across seven moods. Four sources provide fallback classification, with persistent caching and batched requests.'},{title:'Challenges and trade-offs',text:'OAuth refresh, retry logic and rate-limit backoff handle external API constraints. Classification quality depends on available metadata.'}]},
  { _id:'project-pose',slug:'pose-estimation',title:'Pose Estimation',category:'computer-vision',summary:'A rep counter that sees your movement. Every frame stays in your browser.',techs:['MediaPipe','React','WebAssembly','OpenCV'],featured:false,image:'/images/pose-estimation.webp',imageKind:'promo',color:'#badbe8',symbol:'↟',role:'Computer vision & web development',status:'Built', github:'https://github.com/monishpatalay/Pose-Estimation', live:'https://web-ten-xi-38.vercel.app', metrics:[],sections:[{title:'Problem',text:'A rep counter needs to distinguish full movement from partial motion without sending camera frames to a server.'},{title:'Approach',text:'MediaPipe identifies thirty-three body landmarks. Shoulder, elbow and wrist positions determine the elbow angle. A two-stage state machine counts only a full range of motion, independently for each arm.'},{title:'Architecture',text:'Camera → MediaPipe in WebAssembly → joint angles → per-arm state machine → React counter. Inference runs locally.'},{title:'Challenges and trade-offs',text:'Camera angle and occlusion affect landmarks. The original Python and OpenCV notebook was ported into a browser-based workflow.'}]},
  { _id:'project-airbnc',slug:'airbnc',title:'Airbnc',category:'full-stack',summary:'A complete booking flow, from finding a place to making a reservation.',techs:['MongoDB','Express','React','Node.js'],featured:false,imageKind:'promo',color:'#f1c3b8',symbol:'⌂',role:'Full-stack development',status:'Built', github:'https://github.com/monishpatalay/Airbnc', live:'https://airbnc.monishpatalay.dev', metrics:[],sections:[{title:'Problem',text:'A booking platform combines authentication, listings, images and reservations in one coherent user journey.'},{title:'Approach',text:'The MERN application uses JWT authentication, Multer image uploads, REST APIs, and Context API state across reusable React components.'},{title:'Challenges and trade-offs',text:'CRUD-heavy booking workflows require consistent validation and ownership checks. No unverified user-count or performance metrics are claimed.'}]},
  { _id:'project-zyra',slug:'zyra-ai',title:'Zyra AI',category:'web',summary:'An AI chat interface exploring conversational interaction in React.',techs:['React','Context API'],featured:false,imageKind:'promo',color:'#b9c9f0',symbol:'✧',role:'Frontend development',status:'Built', github:'https://github.com/monishpatalay/Zyra', live:'https://zyra.monishpatalay.dev', metrics:[],sections:[{title:'Approach',text:'A frontend chat application with modular React components and shared conversation state.'},{title:'Scope',text:'This project is presented as a frontend implementation. Backend, container deployment, adoption and speed claims from older portfolio copy are intentionally excluded.'}]},
];
export const stats = [
 {value:'700+',label:'DSA problems solved',sourceNote:'Live résumé; platform not specified'},
 {value:'300+',label:'Students mentored',sourceNote:'Live résumé; Smart Interviews'},
 {value:'94.9%',label:'CNN test accuracy',sourceNote:'Crop Expert; single held-out split'},
 {value:'60+',label:'Students supported',sourceNote:'Live résumé; Cal State LA'},
];
export const journey = [
 {role:'Graduate Research Assistant',organization:'Cal State LA',period:'2025 — 2026',location:'Los Angeles, CA',text:'Built automation tools in Google Apps Script for student check-in, assignment distribution, and progress tracking for 60+ students.',bullets:['Replaced manual program workflows end to end','Cut weekly reporting time 30% with scripted Google Sheets data pipelines'],techs:['Google Apps Script','Google Sheets','Automation','Data workflows']},
 {role:'Programming Mentor',organization:'Smart Interviews',period:'2023 — 2024',location:'Hyderabad, India',text:'Mentored 300+ students in data structures and algorithms across 50+ live sessions.',bullets:['Raised average assessment scores 20% through code reviews and mock interviews','Built problem sets and review sheets adopted program-wide'],techs:['C++','Python','Java','Data structures','Algorithms']},
 {role:'Machine Learning Intern',organization:'DRDO',period:'2023',location:'Hyderabad, India',text:'Built a CNN facial-recognition system in TensorFlow and OpenCV at 94% accuracy over 10k+ images.',bullets:['Cut inference latency 20% through preprocessing optimisation','Benchmarked VGG16, ResNet and custom CNNs with runs tracked in MLflow','Deployed through TensorFlow Serving with drift-detection alerts'],techs:['Python','TensorFlow','OpenCV','CNNs','MLflow','TensorFlow Serving']},
];
export const education = [
 {role:'M.S., Computer Science',organization:'California State University, Los Angeles',period:'2024 — 2026',location:'Los Angeles, CA',text:'Completed a Master’s in Computer Science with a 3.9 / 4 GPA, focused on machine learning systems and full-stack software engineering.',bullets:['Graduated with honors','Research in pose estimation using MediaPipe','Coursework spanning machine learning, distributed systems, research, and algorithms'],techs:['Machine learning','Distributed systems','Research','Algorithms']},
 {role:'B.Tech, Artificial Intelligence and Machine Learning',organization:'CMR Engineering College',period:'2020 — 2024',location:'Hyderabad, India',text:'Built a foundation in data structures, systems, and applied artificial intelligence.',bullets:['Coursework: data structures and algorithms, operating systems, databases, machine learning, artificial intelligence, and system design','B.Tech GPA is intentionally omitted until confirmed'],techs:['Data structures','Operating systems','Databases','Machine learning','System design']},
];
export const skillGroups = {
 'Languages':['Python','TypeScript','JavaScript','Java','C++','C','Kotlin','SQL','Bash'],
 'Frontend & backend':['React','Next.js','Node.js','Express','FastAPI','Flask','Django','GraphQL','REST APIs','Microservices','HTML','CSS','Bootstrap'],
 'AI & machine learning':['LLM APIs','RAG','Vector DBs','LangGraph','LangChain','MCP','Structured outputs','Evals','TensorFlow','PyTorch','scikit-learn','Hugging Face','MLflow'],
 'Cloud & data':['AWS','GCP','Docker','PostgreSQL','MongoDB','Redis','GitHub Actions','pytest'],
};

// Achievements shown in the journey chapter and given to the assistant, so the
// page and the chatbot never disagree about what is claimed.
export const achievements = [
 {title:'Published “Pose Estimation using MediaPipe”', detail:'Research paper in IJSREM.', kind:'Publication'},
 {title:'Founder, ICPC Club at CMREC', detail:'Started and ran the competitive-programming club.', kind:'Leadership'},
 {title:'Hackathon finalist', detail:'Reached the final round.', kind:'Competition'},
 {title:'Graduated with honors, M.S.', detail:'3.9 / 4.0 GPA at Cal State LA.', kind:'Academics'},
 {title:'700+ DSA problems solved', detail:'Across platforms including LeetCode.', kind:'Problem solving'},
];

// Curated answers the assistant should prefer over paraphrasing the raw content.
// Editable in Studio as "Chat answer" documents.
export const chatFaqs = [
 {question:'What skills does Monish have?', answer:'Languages: Python, TypeScript, JavaScript, Java, SQL. Frontend & backend: React, Next.js, Node.js, Express.js, FastAPI, REST APIs, microservices. AI & machine learning: LLM APIs (Claude, OpenAI, Gemini, Bedrock), RAG, vector DBs, LangGraph, LangChain, MCP, function calling, PyTorch, scikit-learn, Hugging Face, MLflow. Cloud & DevOps: AWS, GCP, Docker, PostgreSQL, MongoDB, Redis, GitHub Actions, pytest.'},
 {question:'Does Monish know JavaScript or Next.js?', answer:'Yes, he is proficient in both and uses them across full-stack projects, frontend architectures, REST API microservices and workflow automations.'},
 {question:'What is Monish\'s email and phone number?', answer:'Email: officialmonishh@gmail.com. Phone: +1 (626) 692-4003.'},
 {question:'Where is Monish located or based?', answer:'He is based in California, USA, in the Los Angeles area.'},
 {question:'What achievements and publications does Monish have?', answer:'Published “Pose Estimation using MediaPipe” in IJSREM; founder of the ICPC Club at CMREC; hackathon finalist; graduated with honors in his Master\'s with a 3.9/4.0 GPA at Cal State LA; solved over 700 data structures and algorithms problems.'},
 {question:'How many DSA questions has Monish solved?', answer:'Over 700 data structures and algorithms problems across platforms including LeetCode. He has also mentored 300+ students in DSA across C++, Python and Java.'},
 {question:'Where can I find Monish\'s LinkedIn profile?', answer:'His LinkedIn is linked from the contact section of this site: https://www.linkedin.com/in/monish-patalay/'},
 {question:'Where can I find the links and code for his projects?', answer:'Every project has a case study on this site with links to its source and live demo where available, and the code is on his GitHub: https://github.com/monishpatalay'},
 {question:'Tell me about the Airbnc project.', answer:'Airbnc is a full-stack MERN booking platform with JWT authentication, Multer image uploads and complete reservation workflows. He built 15+ reusable React components, managed state with the Context API, and wrote CRUD REST APIs on Express and MongoDB.'},
 {question:'What is Monish\'s educational background and GPA?', answer:'He is completing an M.S. in Computer Science at California State University, Los Angeles (Aug 2024 – May 2026) with a 3.9/4.0 GPA, graduating with honors. He holds a B.Tech in Artificial Intelligence and Machine Learning from CMR Engineering College.'},
];
