'use client';
import {useEffect,useState} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {SplitText} from 'gsap/SplitText';
import {useMotionMode} from '@/lib/motion/governor';
import {dur,stagger} from '@/lib/motion/tokens';
gsap.registerPlugin(ScrollTrigger,SplitText);
const chapters=['hero','statement','numbers','work','journey','skills','try-it','contact'];
export default function HomeMotion(){const {mode}=useMotionMode();const [active,setActive]=useState('hero');useEffect(()=>{const io=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)setActive(entry.target.id);},{rootMargin:'-15% 0px -55% 0px'});chapters.forEach(id=>{const el=document.getElementById(id);if(el)io.observe(el);});if(mode==='calm')return()=>io.disconnect();const ctx=gsap.context(()=>{gsap.utils.toArray<HTMLElement>('.chapter h2').forEach((el,i)=>{const split=SplitText.create(el,{type:i%2?'words,chars':'lines',mask:'lines',autoSplit:true,onSplit:self=>gsap.from(self.lines.length?self.lines:self.chars,{yPercent:100,duration:dur.reveal,stagger:stagger.line,ease:'out',scrollTrigger:{trigger:el,start:'top 90%',once:true}})});return split;});gsap.utils.toArray<HTMLElement>('.stat,.journey-entry,.try-card').forEach(el=>{gsap.from(el,{y:28,duration:dur.slow,ease:'out',scrollTrigger:{trigger:el,start:'top 95%',once:true}});});gsap.utils.toArray<HTMLElement>('.chapter').forEach(el=>{const heading=el.querySelector('h2');if(heading)gsap.fromTo(heading,{y:12},{y:-12,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:true}});});});const mm=gsap.matchMedia();mm.add('(min-width:1024px) and (hover:hover) and (pointer:fine)',()=>{const node=document.querySelector('.journey-list');if(!node)return;gsap.fromTo('.journey-line',{scaleY:0},{scaleY:1,ease:'none',scrollTrigger:{trigger:'#journey',start:'top top',end:'+=150%',pin:true,scrub:true}});});return()=>{io.disconnect();mm.revert();ctx.revert();};},[mode]);return <nav className="chapter-nav" aria-label="Page chapters">{chapters.map(id=><a key={id} href={`#${id}`} aria-label={id.replace('-',' ')} aria-current={active===id} title={id.replace('-',' ')}/>)}</nav>;}
