import {notFound} from 'next/navigation';
import Link from 'next/link';
import {getContent} from '@/lib/content/server';
import {ProjectMedia} from '@/components/rail/ProjectCard';
import RichBody from '@/components/case-study/RichBody';
import {newTabProps} from '@/lib/links';
export async function generateStaticParams(){const {projects}=await getContent();return projects.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const {projects}=await getContent();const project=projects.find(p=>p.slug===slug);return {title:project?.title??'Project not found',description:project?.summary,alternates:{canonical:`/work/${slug}`}};}
export default async function CaseStudy({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const {projects}=await getContent();const index=projects.findIndex(p=>p.slug===slug);if(index<0)notFound();const p=projects[index],next=projects[(index+1)%projects.length];return <main id="main" className="page-shell"><Link href="/work" className="section-kicker">← All work</Link><h1 className="page-title">{p.title}</h1><p className="page-intro">{p.summary}</p><div className="case-meta"><div><small>ROLE</small>{p.role}</div><div><small>STATUS</small>{p.status}</div><div><small>BUILT WITH</small>{p.techs.join(' · ')}</div></div><div className="hero-actions">{p.github&&<a className="button primary" href={p.github} {...newTabProps(p.github)}>Explore the code ↗</a>}{p.live&&<a className="button secondary" href={p.live} {...newTabProps(p.live)}>Visit project ↗</a>}</div><div className="case-hero"><ProjectMedia project={p} priority/></div>{p.metrics.length>0&&<div className="case-metrics">{p.metrics.map(metric=><div className="stat" key={metric.label}><strong className="stat-value">{metric.value}</strong><span className="stat-label">{metric.label}</span><span className="stat-source">{metric.sourceNote}</span></div>)}</div>}<div className="article-layout"><nav className="toc" aria-label="On this page">{p.sections.map((section,i)=><a href={`#section-${i}`} key={section.title}>{section.title}</a>)}</nav><article className="case-body">{p.body?.length?<RichBody value={p.body}/>:p.sections.map((section,i)=><section id={`section-${i}`} key={section.title}><h2>{section.title}</h2><p>{section.text}</p>{section.title==='Architecture'&&<div className="architecture" aria-label="Technology layers">{p.techs.map(tech=><span key={tech}>{tech}</span>)}</div>}</section>)}</article></div><Link href={`/work/${next.slug}`} className="next-project"><small>Keep exploring / next project</small><h2>{next.title} ↗</h2></Link><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'CreativeWork',name:p.title,description:p.summary,author:{'@type':'Person',name:'Monish Patalay'}}).replaceAll('<','\\u003c')}}/></main>;}
