/* eslint-disable react-hooks/immutability */
'use client';
import {Component,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {Canvas,useThree} from '@react-three/fiber';
import * as THREE from 'three';
import {GPUComputationRenderer} from 'three/examples/jsm/misc/GPUComputationRenderer.js';
import gsap from 'gsap';
import {usePathname} from 'next/navigation';
import {useMotionMode,useTier} from '@/lib/motion/governor';
import {dur} from '@/lib/motion/tokens';
import {bakeShape,shapeNames,type ShapeName} from './shapes';
// REPEL_RADIUS is in world units; MORPH_RATE is the slow shape-to-shape blend, REPEL_RATE how fast
// particles near the cursor chase their displaced goal.
const simulation=`#define REPEL_RADIUS .7
#define MORPH_RATE .065
#define REPEL_RATE .34
uniform sampler2D targetShape; uniform vec3 mouse; uniform float time; uniform float calm; uniform float attraction;
void main(){vec2 uv=gl_FragCoord.xy/resolution.xy;vec4 old=texture2D(texturePosition,uv);vec4 target=texture2D(targetShape,uv);vec3 p=old.xyz;vec3 drift=vec3(sin(time*.3+target.w*30.),cos(time*.25+target.w*20.),sin(time*.4+target.w*40.))*.025;vec3 home=target.xyz+drift;vec2 delta=home.xy-mouse.xy;float d=length(delta);float push=smoothstep(REPEL_RADIUS,0.,d)*REPEL_RADIUS;vec3 goal=home+vec3(normalize(delta+vec2(.0001))*push*attraction,0.);float near=smoothstep(REPEL_RADIUS*1.8,REPEL_RADIUS*.6,d);p=mix(p,goal,mix(MORPH_RATE,REPEL_RATE,near));gl_FragColor=vec4(mix(p,target.xyz,calm),1.);}`;
const vertex=`uniform sampler2D positions;uniform float size;attribute vec2 reference;varying float glow;void main(){vec3 p=texture2D(positions,reference).xyz;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=size*(5./-mv.z);glow=.5+reference.x*.5;}`;
const fragment=`varying float glow;uniform vec3 color;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;gl_FragColor=vec4(color, pow(1.-d*2.,1.8)*glow*.65);}`;
function Scene({tier,shape,calm,onFail}:{tier:number;shape:ShapeName;calm:boolean;onFail:()=>void}){
 const {gl,advance,viewport,size}=useThree();const side=tier===3?256:128;const count=side*side;
 const material=useRef<THREE.ShaderMaterial>(null);const shapeRef=useRef(shape);const calmRef=useRef(calm);useEffect(()=>{shapeRef.current=shape;calmRef.current=calm;},[shape,calm]);
 const resources=useMemo(()=>{const gpu=new GPUComputationRenderer(side,side,gl);gpu.setDataType(THREE.HalfFloatType);const initial=gpu.createTexture();initial.image.data!.set(bakeShape('wordmark',count));const variable=gpu.addVariable('texturePosition',simulation,initial);gpu.setVariableDependencies(variable,[variable]);const textures=Object.fromEntries(shapeNames.map(name=>{const tex=new THREE.DataTexture(bakeShape(name,count),side,side,THREE.RGBAFormat,THREE.FloatType);tex.needsUpdate=true;return[name,tex];})) as Record<ShapeName,THREE.DataTexture>;Object.assign(variable.material.uniforms,{targetShape:{value:textures.wordmark},mouse:{value:new THREE.Vector3(100,100,0)},time:{value:0},calm:{value:0},attraction:{value:1}});const reference=new Float32Array(count*2);for(let i=0;i<count;i++){reference[i*2]=(i%side+.5)/side;reference[i*2+1]=(Math.floor(i/side)+.5)/side;}return{gpu,variable,textures,reference,positions:new Float32Array(count*3),error:gpu.init()};},[gl,side,count]);
 useEffect(()=>{if(resources.error){onFail();return;}let last=0;const pointer={x:100,y:100};const mouseTarget=new THREE.Vector3();const move=(event:PointerEvent)=>{pointer.x=(event.clientX/size.width-.5)*viewport.width-(size.width>700?viewport.width*.22:viewport.width*.16);pointer.y=(.5-event.clientY/size.height)*viewport.height;};const tick=(time:number)=>{if(document.hidden)return;if(calmRef.current&&time-last<1)return;last=time;const u=resources.variable.material.uniforms;u.targetShape.value=resources.textures[shapeRef.current];u.time.value=time;u.calm.value=calmRef.current?1:0;u.attraction.value=shapeRef.current==='404'?-1:1;u.mouse.value.lerp(mouseTarget.set(pointer.x,pointer.y,0),.6);resources.gpu.compute();if(material.current)material.current.uniforms.positions.value=resources.gpu.getCurrentRenderTarget(resources.variable).texture;advance(time);};const loss=(event:Event)=>{event.preventDefault();onFail();};gl.domElement.addEventListener('webglcontextlost',loss);addEventListener('pointermove',move,{passive:true});const leave=(event:PointerEvent)=>{if(!event.relatedTarget){pointer.x=100;pointer.y=100;}};document.addEventListener('pointerout',leave);gsap.ticker.add(tick);tick(0);return()=>{gsap.ticker.remove(tick);removeEventListener('pointermove',move);document.removeEventListener('pointerout',leave);gl.domElement.removeEventListener('webglcontextlost',loss);};},[advance,gl,resources,viewport.width,viewport.height,size.width,size.height,onFail]);
 return <points position={[size.width>700?viewport.width*.22:viewport.width*.16,0,0]}><bufferGeometry><bufferAttribute attach="attributes-position" args={[resources.positions,3]}/><bufferAttribute attach="attributes-reference" args={[resources.reference,2]}/></bufferGeometry><shaderMaterial ref={material} vertexShader={vertex} fragmentShader={fragment} uniforms={{positions:{value:null},size:{value:tier===3?2.4:3.2},color:{value:new THREE.Color('#c2a4ff')}}} transparent depthWrite={false} blending={THREE.AdditiveBlending}/></points>;
}
class Boundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}
export default function ParticleCanvas(){const tier=useTier();const {mode}=useMotionMode();const path=usePathname();const [ready,setReady]=useState(false),[failed,setFailed]=useState(false),[shape,setShape]=useState<ShapeName>('wordmark');const fail=useMemo(()=>()=>setFailed(true),[]);
 useEffect(()=>{const timeout=setTimeout(()=>setReady(true),dur.reveal*1000);return()=>clearTimeout(timeout);},[]);
 useEffect(()=>{if(path!=='/'){queueMicrotask(()=>setShape(path==='/work'?'grid':path==='/playground'?'brain':path.startsWith('/work/')?'sphere':'404'));return;}queueMicrotask(()=>setShape('wordmark'));const io=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){const name=(entry.target as HTMLElement).dataset.shape as ShapeName;if(shapeNames.includes(name))setShape(name);}},{rootMargin:'-20% 0px -45% 0px'});document.querySelectorAll('[data-shape]').forEach(el=>io.observe(el));return()=>io.disconnect();},[path]);
 const poster=<div className="particle-poster"/>;return <div className="particle-shell" aria-hidden="true">{poster}{ready&&tier>1&&!failed&&<Boundary fallback={poster}><Canvas frameloop="never" camera={{position:[0,0,7],fov:50}} dpr={[1,tier===3?2:1.5]} gl={{alpha:true,antialias:false,powerPreference:'low-power'}}><Scene tier={tier} shape={shape} calm={mode==='calm'} onFail={fail}/></Canvas></Boundary>}</div>;
}
