'use client';
import Image from 'next/image';
import Link from 'next/link';
import gsap from 'gsap';
import {createElement,useEffect,useRef,type CSSProperties} from 'react';
import type {Project} from '@/lib/content/data';
import {newTabProps} from '@/lib/links';
import {useMotionMode} from '@/lib/motion/governor';
export function ProjectMedia({project,priority=false}:{project:Project;priority?:boolean}){const fallback=project.slug==='spotify-library-organizer'?'spotify':project.slug==='airbnc'?'airbnc':null;const muxId=project.previewPlaybackId,previewVideo=(fallback?`/videos/${fallback}-preview.mp4`:undefined),poster=muxId?`https://image.mux.com/${muxId}/thumbnail.webp?width=960&time=${project.previewThumbTime??0}`:fallback?`/videos/${fallback}-preview-poster.jpg`:undefined;return <div className="project-media" style={{'--project-color':project.color,viewTransitionName:`cover-${project.slug}`} as CSSProperties}>{project.image?<Image src={project.image} alt={`${project.title} — promotional concept artwork`} fill sizes="(min-width: 1024px) 43vw, 86vw" priority={priority}/>:<div className="project-art" aria-hidden="true"><span className="art-symbol">{project.symbol}</span><div className="art-frame"><small>{project.category==='ai-ml'?'MACHINE LEARNING, MADE USEFUL':'THOUGHTFULLY BUILT'}</small><div className="art-word">{project.title}</div><div className="art-lines"><i/><i/><i/></div></div></div>}{muxId?createElement('mux-video',{className:'project-preview-video','playback-id':muxId,poster,muted:true,loop:true,playsinline:true,preload:'none','disable-tracking':true,'aria-hidden':'true'}):previewVideo&&<video className="project-preview-video" src={previewVideo} poster={poster} muted loop playsInline preload="none" aria-hidden="true"/>}</div>;}
export default function ProjectCard({project,index=0}:{project:Project;index?:number}){const {mode}=useMotionMode(),cardRef=useRef<HTMLElement>(null);useEffect(()=>{const card=cardRef.current,video=card?.querySelector<HTMLVideoElement>('video, mux-video');if(!card||!video)return;const load=()=>{if(video.localName==='mux-video'){import('@mux/mux-video').then(()=>customElements.whenDefined('mux-video')).then(()=>{video.preload='auto';}).catch(()=>{});return;}video.preload='auto';if(video.paused&&video.readyState===0)video.load();};if(!('IntersectionObserver'in window)){load();return;}const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){load();observer.disconnect();}},{rootMargin:'600px'});observer.observe(card);return()=>observer.disconnect();},[project.previewPlaybackId,project.slug]);return <article ref={cardRef} className="rail-card" data-cursor-label="View" onMouseEnter={event=>{const video=event.currentTarget.querySelector<HTMLVideoElement>('video, mux-video');if(!video||mode==='calm')return;video.play?.()?.catch(()=>{});gsap.killTweensOf(video);gsap.to(video,{autoAlpha:1,scale:1,y:0,rotateX:0,clipPath:'inset(0% 0% round 14px)',transformPerspective:900,duration:.55,ease:'power3.out'});}} onMouseLeave={event=>{const video=event.currentTarget.querySelector<HTMLVideoElement>('video, mux-video');if(!video)return;video.pause?.();gsap.killTweensOf(video);if(mode==='calm')gsap.set(video,{autoAlpha:0});else gsap.to(video,{autoAlpha:0,scale:.84,y:18,rotateX:-8,clipPath:'inset(12% 10% round 22px)',transformPerspective:900,duration:.35,ease:'power2.inOut'});}}><ProjectMedia project={project}/><div className="project-info"><div className="project-meta"><span>{String(index+1).padStart(2,'0')} / {project.category.replaceAll('-',' ').toUpperCase()}</span><span>{project.status}</span></div><h3 className="project-title"><Link href={`/work/${project.slug}`}>{project.title}</Link></h3><p className="project-summary">{project.summary}</p><div className="tags">{project.techs.slice(0,4).map(tech=><span className="tag" key={tech}>{tech}</span>)}</div><div className="project-links">{project.github&&<a href={project.github} {...newTabProps(project.github)}>Code ↗</a>}{project.live&&<a href={project.live} {...newTabProps(project.live)}>Live project ↗</a>}</div></div></article>;}
