'use client';
import {PortableText,type PortableTextComponents} from '@portabletext/react';
import type {PortableTextBlock} from '@portabletext/types';
import {useRef,useState} from 'react';
import {newTabProps} from '@/lib/links';
function Figure({value}:{value:{url:string;alt:string;caption?:string}}){const dialog=useRef<HTMLDialogElement>(null);return <figure><button onClick={()=>dialog.current?.showModal()} aria-label={`Enlarge ${value.alt}`}><img src={value.url} alt={value.alt} width={1200} height={750}/></button>{value.caption&&<figcaption>{value.caption}</figcaption>}<dialog ref={dialog}><button onClick={()=>dialog.current?.close()} className="button">Close</button><img src={value.url} alt={value.alt} width={1200} height={750}/></dialog></figure>;}
function Code({value}:{value:{code:string;language?:string}}){const [copied,setCopied]=useState(false);return <div><button className="chip" onClick={async()=>{try{await navigator.clipboard.writeText(value.code);setCopied(true);}catch{setCopied(false);}}}>{copied?'Copied':'Copy code'}</button><pre><code>{value.code}</code></pre></div>;}
function Compare({value}:{value:{before:string;after:string;alt:string}}){const [position,setPosition]=useState(50);return <figure><div style={{position:'relative'}}><img src={value.before} alt={`Before: ${value.alt}`} width={1200} height={750}/><img src={value.after} alt={`After: ${value.alt}`} width={1200} height={750} style={{position:'absolute',inset:0,clipPath:`inset(0 ${100-position}% 0 0)`}}/></div><label>Compare before and after <input type="range" min="0" max="100" step="5" value={position} onChange={e=>setPosition(Number(e.target.value))}/></label></figure>;}
const components:PortableTextComponents={types:{callout:({value})=><aside className="journey-entry"><strong>{value.variant}</strong><p>{value.text}</p></aside>,figure:Figure,codeBlock:Code,compare:Compare,divider:()=> <hr/>,gallery:({value})=><div className="try-grid">{value.images.map((image:{url:string;alt:string},i:number)=><Figure key={i} value={image}/>)}</div>,metricsRow:({value})=><div className="case-metrics">{value.metrics.map((m:{label:string;value:string})=><div className="stat" key={m.label}><strong className="stat-value">{m.value}</strong>{m.label}</div>)}</div>,video:({value})=><video src={value.url} poster={value.poster} controls muted playsInline preload="none"/>},marks:{link:({value,children})=>{const href=typeof value?.href==='string'&&/^(https:\/\/|\/(?!\/)|mailto:)/.test(value.href)?value.href:'#';return <a href={href} {...newTabProps(href)}>{children}</a>;}}};
export default function RichBody({value}:{value:unknown[]}){return <PortableText value={value as PortableTextBlock[]} components={components}/>;}
